[package]
name = "tolkien"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
egui_json_tree = "0.11.0"
inquire = "0.7.5"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
petgraph = "0.7.1"
