[package]
name = "tolkien"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
grammarconversion = "0.2.0"
pyo3 = "0.24.0"
ratatui = "0.29.0"
rayon = "1.10.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
