[package]
name = "gram"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["full"] }
rand = "0.9.0"
inquire = "0.7.5"
csv = "1.3.1"

